# Generated by Django 3.0.5 on 2021-03-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_antipasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BURGUR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
